// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSSwk1iFzE8-4eSxn22swkXBM_NTJXnHQ',
    appId: '1:295012865924:web:5d8bf45cf7fbf3b81defd1',
    messagingSenderId: '295012865924',
    projectId: 'learningdart-flutter-again',
    authDomain: 'learningdart-flutter-again.firebaseapp.com',
    storageBucket: 'learningdart-flutter-again.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjOiq0BHs_BNISymgWaIB7PAjLbWp1v_U',
    appId: '1:295012865924:android:9314c2f5a8210c7b1defd1',
    messagingSenderId: '295012865924',
    projectId: 'learningdart-flutter-again',
    storageBucket: 'learningdart-flutter-again.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpclH13gaMFwIVleAji1IaaJFE3fPHpVk',
    appId: '1:295012865924:ios:7285aee008ea6bd91defd1',
    messagingSenderId: '295012865924',
    projectId: 'learningdart-flutter-again',
    storageBucket: 'learningdart-flutter-again.appspot.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpclH13gaMFwIVleAji1IaaJFE3fPHpVk',
    appId: '1:295012865924:ios:7285aee008ea6bd91defd1',
    messagingSenderId: '295012865924',
    projectId: 'learningdart-flutter-again',
    storageBucket: 'learningdart-flutter-again.appspot.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSSwk1iFzE8-4eSxn22swkXBM_NTJXnHQ',
    appId: '1:295012865924:web:78e4765484e0c70a1defd1',
    messagingSenderId: '295012865924',
    projectId: 'learningdart-flutter-again',
    authDomain: 'learningdart-flutter-again.firebaseapp.com',
    storageBucket: 'learningdart-flutter-again.appspot.com',
  );
}
